/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     hbpkg.h
 * \Author   ronghui.zhang
 * \Mail     ronghui.zhang@horizon.ai
 * \Version  1.0.0.0
 * \Date     2019-11-11
 * \Brief    Hbpkg test code
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#include <string>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "xpluginflow/hbpkg/hobot_utililty.h"
#include "xpluginflow/hbpkg/opkg_conf.h"
#include "xpluginflow/hbpkg/opkg_cmd.h"
#include "xpluginflow/hbpkg/opkg_message.h"
#include "xpluginflow/hbpkg/opkg_download.h"

enum {
	AP_PLATFORM = 0,
	CP_PLATFORM,
};

class Hbpkg {
public:
	Hbpkg();
	~Hbpkg();

	int hbpkg_init();
	int hbpkg_deinit();
	int hbpkg_process(std::string fileName, int platform);
	int hbpkg_install(std::string fileName, int platform);
	int hbpkg_uninstall();
	int hbpkg_update();
	int hbpkg_getVersion();
	int hbpkg_unzip(std::string fileName);
	int hbpkg_sendPkg(std::string fileName);
	int hbpkg_checkMD5(std::string fileName, std::string md5Sum);
private:
	
};
 
